let CATS=['娱乐','吃喝','房租','衣服','日常','交通','医疗','学习','其他'];
const CURRENCIES={CNY:'人民币',USD:'美元',EUR:'欧元',JPY:'日元',HKD:'港币',GBP:'英镑',KRW:'韩元',SGD:'新加坡元',AUD:'澳元',CAD:'加元',CHF:'瑞士法郎'};
const icons={娱乐:'♪',吃喝:'🍜',房租:'⌂',衣服:'◌',日常:'⌁',交通:'↗',医疗:'＋',学习:'✦',其他:'•',收入:'＋'};
let user='', records=[], currentType='expense', activeFilter='all', period='month', ocrItems=[], ocrDetectedCurrency='CNY';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function key(){return `ledger:${user}`}
async function saveRecord(record){const res=await fetch(`/api/users/${encodeURIComponent(user)}/records`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(record)});const data=await res.json().catch(()=>null);if(!res.ok)throw new Error(data?.error||'保存失败');return data}
async function removeRecord(id){const res=await fetch(`/api/users/${encodeURIComponent(user)}/records/${encodeURIComponent(id)}`,{method:'DELETE'});if(!res.ok)throw new Error('删除失败')}
function money(n,c='CNY'){try{const digits=Math.abs(Number(n))<1&&Number(n)!==0?4:2;return new Intl.NumberFormat('zh-CN',{style:'currency',currency:c,maximumFractionDigits:digits}).format(Number(n))}catch{return `${c} ${Number(n).toFixed(4)}`}}
function dateLabel(v){return new Date(`${v}T12:00:00`).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}
function today(){return new Date().toISOString().slice(0,10)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderQuickCategories(){const grid=$('#quickGrid');if(!grid)return;const items=CATS.slice(0,3).map((cat,index)=>`<button class="quick-item" data-type="expense" data-cat="${escapeHtml(cat)}"><span class="quick-icon ${['coral','blue','green'][index]}">${icons[cat]||'•'}</span><b>${escapeHtml(cat)}</b><small>记录一笔</small></button>`).join('');grid.innerHTML=items+`<button class="quick-item" data-type="income" data-cat="收入"><span class="quick-icon yellow">＋</span><b>收入</b><small>记录一笔</small></button>`;bindQuickItems()}
function bindQuickItems(){$$('.quick-item').forEach(button=>{button.setAttribute('aria-label',`记录${button.dataset.cat}`);button.onclick=()=>openModal(button.dataset.type,button.dataset.cat)})}
function fillCategories(){const select=$('#category'),filter=$('#categoryFilter');if(!select||!filter)return;select.innerHTML=CATS.map(c=>`<option>${escapeHtml(c)}</option>`).join('');filter.innerHTML='<option value="all">全部分类</option>'+CATS.map(c=>`<option>${escapeHtml(c)}</option>`).join('');renderQuickCategories()}
function renderCategoryManager(){const list=$('#categoryList');if(!list)return;list.innerHTML=CATS.map(category=>`<div class="category-row"><input value="${escapeHtml(category)}" maxlength="20" data-category-input="${escapeHtml(category)}"><button class="outline-btn" type="button" data-rename-category="${escapeHtml(category)}">改名</button></div>`).join('')}
async function changeCategory(action,oldName,newName){const res=await fetch(`/api/users/${encodeURIComponent(user)}/categories`,{method:'PUT',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({action,oldName,newName})});const data=await res.json().catch(()=>null);if(!res.ok)throw new Error(data?.error||'分类保存失败');if(action==='rename')records=records.map(record=>record.category===oldName?{...record,category:newName}:record);CATS=data.categories;fillCategories();renderCategoryManager();render();toast(action==='rename'?'分类名称已同步到当前账户':'分类已添加')}
function openCategoryManager(){renderCategoryManager();$('#categoryModal').classList.remove('hidden')}
function closeCategoryManager(){$('#categoryModal').classList.add('hidden')}
function fillCurrencies(){const options=Object.entries(CURRENCIES).map(([code,name])=>`<option value="${code}">${code} · ${name}</option>`).join('');$('#sourceCurrency').innerHTML=options;$('#targetCurrency').innerHTML=options;const base=localStorage.getItem('ledger:base-currency')||'CNY';$('#sourceCurrency').value=base;$('#targetCurrency').value=base}
const rateCache=new Map();
async function getRate(base,target){if(base===target)return 1;const key=`${base}:${target}`;if(rateCache.has(key))return rateCache.get(key);const res=await fetch(`/api/rates?base=${base}&symbols=${target}`);if(!res.ok)throw new Error('汇率服务暂不可用');const data=await res.json();const rate=Number(data.rates?.[target]);if(!rate)throw new Error('未找到该货币汇率');rateCache.set(key,rate);return rate}
async function updateExchangePreview(){const amount=Number($('#amount').value)||0,base=$('#sourceCurrency').value,target=$('#targetCurrency').value;try{const rate=await getRate(base,target);$('#exchangePreview').textContent=`1 ${base} = ${rate.toFixed(6)} ${target} · 记账金额 ${money(amount*rate,target)}`}catch{$('#exchangePreview').textContent='汇率暂时不可用，将按原金额保存，请稍后重试'} }
function openModal(type='expense',cat=CATS[0],ocr=''){ocrItems=[];ocrDetectedCurrency='CNY';currentType=type;$('#entryModal').classList.remove('hidden');$('#amount').value='';$('#note').value='';$('#date').value=today();fillCategories();$('#category').value=CATS.includes(cat)?cat:CATS[0];$('#ocrStatus').classList.toggle('hidden',!ocr);$('#ocrStatus').textContent=ocr||'';$('#ocrItemsPreview').classList.add('hidden');$('#ocrItemsPreview').innerHTML='';fillCurrencies();$$('.type-btn').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$('#modalTitle').textContent=ocr?'确认识别结果':'新增一笔';$('#amount').focus()}
function closeModal(){$('#entryModal').classList.add('hidden')}
async function addRecord(e){e.preventDefault();const requestedCurrency=$('#targetCurrency').value;const drafts=ocrItems.length?ocrItems.map(item=>({...item,type:currentType,date:$('#date').value})): [{type:currentType,amount:Number($('#amount').value),category:$('#category').value,note:$('#note').value.trim()||$('#category').value,originalNote:'',sourceCurrency:$('#sourceCurrency').value,date:$('#date').value}];try{localStorage.setItem('ledger:base-currency',requestedCurrency);const saved=[];let allConverted=true;for(const draft of drafts){const sourceCurrency=draft.sourceCurrency||$('#sourceCurrency').value;let targetCurrency=requestedCurrency,rate=1;try{rate=await getRate(sourceCurrency,requestedCurrency)}catch{targetCurrency=sourceCurrency;allConverted=false}saved.push(await saveRecord({...draft,sourceAmount:Number(draft.amount),sourceCurrency,currency:targetCurrency,exchangeRate:rate,amount:Number(draft.amount)*rate,note:([draft.originalNote&&`原文：${draft.originalNote}`,draft.note].filter(Boolean).join(' · ')||draft.category).slice(0,50)}))}records.unshift(...saved.reverse());closeModal();render();toast(allConverted?(saved.length>1?`已同步 ${saved.length} 项账目`:'已同步到云端'):(saved.length>1?`部分汇率暂不可用，已保存 ${saved.length} 项`:'汇率暂不可用，已按原货币保存'))}catch(err){toast(err.message==='Failed to fetch'?'云端服务未连接，请稍后重试':'云端保存失败，请稍后重试')}}
function filtered(){const cat=$('#categoryFilter').value;return records.filter(r=>(activeFilter==='all'||r.type===activeFilter)&&(cat==='all'||r.category===cat))}
function txHtml(r,del=true){return `<div class="transaction"><span class="tx-icon ${r.type==='income'?'green':'coral'}">${icons[r.category]||'•'}</span><div class="tx-main"><b>${r.note||r.category}</b><small>${r.category} · ${dateLabel(r.date)}${r.sourceCurrency&&r.sourceCurrency!==r.currency?` · ${r.sourceAmount} ${r.sourceCurrency}`:''}</small></div><strong class="tx-amount ${r.type}">${r.type==='income'?'+':'-'}${money(r.amount,r.currency||'CNY')}</strong>${del?`<button class="delete-btn" data-delete="${r.id}" title="删除"><i data-lucide="trash-2"></i></button>`:''}</div>`}
function renderHome(){const ym=today().slice(0,7), rs=records.filter(r=>r.date.startsWith(ym)), inc=rs.filter(r=>r.type==='income').reduce((a,r)=>a+r.amount,0), exp=rs.filter(r=>r.type==='expense').reduce((a,r)=>a+r.amount,0);$('#currentMonth').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long'});$('#todayLabel').textContent=dateLabel(today());$('#monthBalance').textContent=money(inc-exp);$('#monthIncome').textContent=`收入 ${money(inc)}`;$('#monthExpense').textContent=`支出 ${money(exp)}`;$('#recentList').innerHTML=records.slice(0,5).map(r=>txHtml(r,false)).join('')||'<div class="empty">还没有记录，先记下今天的第一笔吧。</div>'}
function renderLedger(){$('#ledgerList').innerHTML=filtered().map(r=>txHtml(r)).join('')||'<div class="empty">没有符合条件的记录。</div>'}
function renderDashboard(){const now=new Date(), val=$('#periodSelect').value||now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0'), rs=records.filter(r=>period==='year'?r.date.startsWith(val):r.date.startsWith(val)), exp=rs.filter(r=>r.type==='expense'),inc=rs.filter(r=>r.type==='income'), totalExp=exp.reduce((a,r)=>a+r.amount,0),totalInc=inc.reduce((a,r)=>a+r.amount,0), groups=CATS.map(c=>[c,exp.filter(r=>r.category===c).reduce((a,r)=>a+r.amount,0)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);let angle=0,colors=['#e9644c','#e6b65a','#79a77e','#76a5c9','#8d7aac','#d18c68'];const parts=groups.map((g,i)=>{const start=angle;angle+=totalExp?g[1]/totalExp*100:0;return `${colors[i%colors.length]} ${start}% ${angle}%`}).join(',')||'#ddd 0 100%';$('#dashboardContent').innerHTML=`<div class="chart-wrap"><div class="donut" style="background:conic-gradient(${parts})"><span>${money(totalExp)}</span></div><div class="legend">${groups.slice(0,5).map((g,i)=>`<div class="legend-row"><span><i class="dot" style="background:${colors[i%colors.length]}"></i>${g[0]}</span><b>${money(g[1])}</b></div>`).join('')||'<div class="muted">该时段暂无支出</div>'}</div></div><table class="stat-table"><tbody><tr><td>总收入</td><td class="income">${money(totalInc)}</td></tr><tr><td>总支出</td><td>${money(totalExp)}</td></tr><tr class="table-total"><td>实际结余</td><td>${money(totalInc-totalExp)}</td></tr>${groups.map(g=>`<tr><td>${g[0]} · ${((g[1]/(totalExp||1))*100).toFixed(1)}%</td><td>${money(g[1])}</td></tr>`).join('')}</tbody></table><div class="section-head"><h3>金额最大的 10 笔</h3><span class="muted">${period==='year'?'年度':'月度'}</span></div><div class="top-list">${[...rs].sort((a,b)=>b.amount-a.amount).slice(0,10).map(r=>`<div class="top-row"><div class="tx-main"><b>${r.note}</b><small>${r.category} · ${dateLabel(r.date)}</small></div><strong class="tx-amount ${r.type}">${r.type==='income'?'+':'-'}${money(r.amount)}</strong></div>`).join('')||'<div class="empty">还没有可分析的交易。</div>'}</div>`}
function renderPeriodSelect(){const y=new Date().getFullYear();$('#periodSelect').innerHTML=period==='year'?Array.from({length:5},(_,i)=>`<option>${y-i}</option>`).join(''):Array.from({length:12},(_,i)=>{const d=new Date(y,i,1);return `<option value="${y}-${String(i+1).padStart(2,'0')}">${y}年${i+1}月</option>`}).join('');renderDashboard()}
function render(){renderHome();renderLedger();renderPeriodSelect();lucide.createIcons()}
function guessCategory(text){return CATS.find(c=>text.includes(c))||(['猪肉','牛肉','鸡','菜','饭','餐','奶茶','咖啡','水果','超市'].some(x=>text.includes(x))?'吃喝':['地铁','公交','打车','滴滴','高铁','火车','停车'].some(x=>text.includes(x))?'交通':['房租','租金'].some(x=>text.includes(x))?'房租':['电影','游戏','门票'].some(x=>text.includes(x))?'娱乐':'其他')}
function detectReceiptCurrency(text){if(/[円¥￥]|JPY|日元|日本円|円(税込|tax)/i.test(text)||/[\u3040-\u30ff]/.test(text))return 'JPY';if(/[$＄]|USD|美元|dollar/i.test(text))return 'USD';if(/[€]|EUR|欧元|euro/i.test(text))return 'EUR';if(/[₩]|KRW|韩元|원/i.test(text))return 'KRW';if(/[港幣港币]|HKD/i.test(text))return 'HKD';if(/[英镑]|GBP|£/i.test(text))return 'GBP';return 'CNY'}
function parseOcrLines(text){const docCurrency=detectReceiptCurrency(text),skip=/^(合计|总计|应付|实付|找零|税额|税率|优惠|折扣|发票|订单|支付|二维码|收款|金额|小计|服务费|電話|电话|住所|地址|取引日時|交易日期|レシート番号|收银员|tel|fax|www\.)/i;const metadata=/(^|\s)(\d{3,4}[-－]\d{3,4}|\d{4}[\/-]\d{1,2}[\/-]\d{1,2}|\d{1,2}:\d{2}|〒\d|邮编|郵便番号|电话|電話|tel|fax)(\s|$)/i;const amountPattern=/(?:[¥￥$€£₩]|JPY|USD|EUR|GBP|KRW|CNY|人民币|日元|円)?\s*(\d{1,3}(?:[,.]\d{3})*(?:\.\d{1,2})?|\d+(?:\.\d{1,2})?)\s*(?:元|円|¥|￥|usd|rmb|jpy|eur|gbp|krw)?\s*$/i;return text.split(/\r?\n/).map(line=>line.replace(/\s+/g,' ').trim()).filter(line=>line&&!skip.test(line)&&!metadata.test(line)).map(line=>{const match=line.match(amountPattern);if(!match)return null;const amount=Number(match[1].replace(/,/g,''));let note=line.slice(0,match.index).replace(/^\d+[.、)）]\s*/,'').replace(/[|:：*x×]+$/,'').trim();if(!note||/^(\d+[/-]?)+$/.test(note)||amount<=0||amount>=1000000)return null;return {amount,category:guessCategory(note),note,originalNote:note,sourceCurrency:docCurrency}}).filter(Boolean)}
async function translateToChinese(text){if(!text||/[\u4e00-\u9fff]/.test(text))return text;try{const q=encodeURIComponent(text.slice(0,300));const res=await fetch(`https://api.mymemory.translated.net/get?q=${q}&langpair=autodetect|zh-CN`);const data=await res.json();return data.responseData?.translatedText||text}catch{return text}}
function renderOcrItems(){const preview=$('#ocrItemsPreview');if(!ocrItems.length){preview.classList.add('hidden');preview.innerHTML='';return}const currencyOptions=Object.entries(CURRENCIES).map(([code,name])=>`<option value="${code}">${code} · ${name}</option>`).join('');preview.classList.remove('hidden');preview.innerHTML=`<div class="ocr-toolbar"><b>待提交账目（${ocrItems.length} 项）</b><label>批量原始货币<select id="ocrBatchCurrency"><option value="">不批量修改</option>${currencyOptions}</select></label></div>`+ocrItems.map((item,index)=>`<div class="ocr-item" data-ocr-index="${index}"><input class="ocr-amount" type="number" min="0.01" step="0.01" value="${item.amount}" aria-label="第${index+1}项金额"><div class="ocr-edit-main"><input class="ocr-note" value="${escapeHtml(item.note||'识别账目')}" aria-label="第${index+1}项中文备注"><small class="ocr-original">原文：${escapeHtml(item.originalNote||item.note||'')}</small><select class="ocr-category" aria-label="第${index+1}项分类">${CATS.map(cat=>`<option ${cat===item.category?'selected':''}>${escapeHtml(cat)}</option>`).join('')}</select><select class="ocr-currency" aria-label="第${index+1}项原始货币">${currencyOptions}</select></div><button class="ocr-delete" type="button" title="删除这一项" aria-label="删除第${index+1}项"><i data-lucide="trash-2"></i></button></div>`).join('');$$('.ocr-currency').forEach((select,index)=>select.value=ocrItems[index].sourceCurrency||ocrDetectedCurrency);lucide.createIcons()}
function bindOcrEditor(){const preview=$('#ocrItemsPreview');preview.addEventListener('input',event=>{const row=event.target.closest('[data-ocr-index]');if(!row)return;const item=ocrItems[Number(row.dataset.ocrIndex)];if(event.target.classList.contains('ocr-amount'))item.amount=Number(event.target.value);if(event.target.classList.contains('ocr-note'))item.note=event.target.value});preview.addEventListener('change',event=>{const row=event.target.closest('[data-ocr-index]');if(event.target.id==='ocrBatchCurrency'&&event.target.value){ocrItems.forEach(item=>item.sourceCurrency=event.target.value);renderOcrItems();return}if(!row)return;const item=ocrItems[Number(row.dataset.ocrIndex)];if(event.target.classList.contains('ocr-category'))item.category=event.target.value;if(event.target.classList.contains('ocr-currency'))item.sourceCurrency=event.target.value});preview.addEventListener('click',event=>{const button=event.target.closest('.ocr-delete');if(!button)return;const row=button.closest('[data-ocr-index]');ocrItems.splice(Number(row.dataset.ocrIndex),1);renderOcrItems();$('#ocrStatus').textContent=`还剩 ${ocrItems.length} 项待提交。`})}
async function recognize(file){openModal('expense','吃喝');$('#ocrStatus').classList.remove('hidden');$('#ocrStatus').textContent='正在识别多语言账目、过滤地址电话并转换为中文…';try{const {data}=await Tesseract.recognize(file,'eng+chi_sim+jpn+kor+spa+fra+deu+rus+por+ita');const text=data.text||'';ocrDetectedCurrency=detectReceiptCurrency(text);ocrItems=await Promise.all(parseOcrLines(text).map(async item=>({...item,note:await translateToChinese(item.note)})));if(ocrItems.length){const first=ocrItems[0];fillCurrencies();$('#sourceCurrency').value=ocrDetectedCurrency;$('#targetCurrency').value=localStorage.getItem('ledger:base-currency')||'CNY';$('#amount').value=first.amount;$('#category').value=first.category;$('#note').value=first.note;renderOcrItems();$('#ocrStatus').textContent=`识别到 ${ocrDetectedCurrency}，已生成 ${ocrItems.length} 项可编辑账目；原文保留在每项下方。`}else{$('#ocrStatus').textContent='未识别到可靠的逐行金额，请手动填写第一笔。';$('#note').value=text.replace(/\s+/g,' ').trim().slice(0,50)}}catch(err){$('#ocrStatus').textContent='识别服务暂时不可用，请手动填写账目。'}}
$('#logoutBtn').onclick=()=>{user='';localStorage.removeItem('ledger:current-user');records=[];$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden');$('#username').focus()};$('#quickAdd').onclick=()=>openModal();$('#viewAll').onclick=()=>switchTab('ledgerTab');$('#uploadBtn').onclick=()=>$('#receiptInput').click();$('#receiptInput').onchange=e=>e.target.files[0]&&recognize(e.target.files[0]);$('#entryForm').onsubmit=addRecord;$('.close-modal').onclick=closeModal;$('.modal-backdrop').onclick=closeModal;$$('.type-btn').forEach(b=>b.onclick=()=>{currentType=b.dataset.type;$$('.type-btn').forEach(x=>x.classList.toggle('active',x===b))});$$('.nav-item').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));function switchTab(id){$$('.tab-page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));render()};$$('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderLedger();lucide.createIcons()});$('#categoryFilter').onchange=renderLedger;$$('.period').forEach(b=>b.onclick=()=>{period=b.dataset.period;$$('.period').forEach(x=>x.classList.toggle('active',x===b));renderPeriodSelect()});$('#periodSelect').onchange=renderDashboard;$('#manageCategoriesBtn').onclick=openCategoryManager;$('#closeCategoryModal').onclick=closeCategoryManager;$('#categoryModal .modal-backdrop').onclick=closeCategoryManager;$('#addCategoryBtn').onclick=async()=>{const input=$('#newCategoryName'),name=input.value.trim();if(!name)return toast('请输入分类名称');try{await changeCategory('add','',name);input.value=''}catch(error){toast(error.message)}};document.addEventListener('click',async event=>{const button=event.target.closest('[data-rename-category]');if(!button)return;const oldName=button.dataset.renameCategory,newName=$(`[data-category-input="${CSS.escape(oldName)}"]`)?.value.trim();if(!newName)return toast('请输入分类名称');try{await changeCategory('rename',oldName,newName)}catch(error){toast(error.message)}});fillCategories();lucide.createIcons();
const remembered=localStorage.getItem('ledger:current-user');if(remembered)$('#username').value=remembered;
let loginBusy=false;
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(loginBusy)return;loginBusy=true;const name=$('#username').value.trim(),password=$('#password').value;$('#loginError').textContent='';try{const res=await fetch('/api/account',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:name,password})});const type=res.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('当前页面不是云端服务，请先用 npm start 启动 Node 服务');const data=await res.json();if(!res.ok)throw new Error(data.error||'登录失败');user=data.username;records=data.records;CATS=Array.isArray(data.categories)&&data.categories.length?data.categories:CATS;fillCategories();localStorage.setItem('ledger:current-user',user);$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=user;$('#greeting').textContent='你的记录，只在这里';render()}catch(err){localStorage.removeItem('ledger:current-user');$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden');$('#loginError').textContent=err.message==='Failed to fetch'?'云端服务未连接，请稍后再试':err.message}finally{loginBusy=false}});
$('#togglePassword').onclick=()=>{const input=$('#password'),button=$('#togglePassword');input.type=input.type==='password'?'text':'password';button.setAttribute('aria-label',input.type==='password'?'显示密码':'隐藏密码');button.innerHTML=`<i data-lucide="${input.type==='password'?'eye':'eye-off'}"></i>`;lucide.createIcons()};
$('#amount').addEventListener('input',updateExchangePreview);$('#sourceCurrency').addEventListener('change',updateExchangePreview);$('#targetCurrency').addEventListener('change',updateExchangePreview);
document.addEventListener('click',async e=>{const btn=e.target.closest('[data-delete]');if(btn&&confirm('确定删除这笔记录吗？')){try{await removeRecord(btn.dataset.delete);records=records.filter(r=>r.id!==btn.dataset.delete);render();toast('记录已删除')}catch(err){toast(err.message==='Failed to fetch'?'云端服务未连接，请稍后重试':(err.message||'云端删除失败，请稍后重试'))}}});
let cameraStream=null;
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){toast('当前浏览器不支持网页摄像头');return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:960}},audio:false});$('#cameraVideo').srcObject=cameraStream;$('#cameraModal').classList.remove('hidden')}catch(err){toast(location.protocol==='http:'&&!['localhost','127.0.0.1'].includes(location.hostname)?'拍照需要 HTTPS 安全连接':'请允许浏览器使用摄像头')}}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}$('#cameraVideo').srcObject=null;$('#cameraModal').classList.add('hidden')}
async function captureCamera(){const video=$('#cameraVideo');if(!video.videoWidth){toast('摄像头画面还未准备好');return}const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));stopCamera();recognize(blob)}
$('#cameraBtn').onclick=startCamera;$('#captureBtn').onclick=captureCamera;$('.close-camera').onclick=stopCamera;$('.camera-backdrop').onclick=stopCamera;
bindQuickItems();

// Batch OCR keeps all recognized rows in one confirmation and cloud-save action.
async function recognizeFiles(files){const list=[...files].filter(Boolean);if(!list.length)return;openModal('expense','吃喝');$('#ocrStatus').classList.remove('hidden');$('#ocrStatus').textContent=`正在识别 ${list.length} 张图片，请稍候…`;try{const texts=[];for(let i=0;i<list.length;i++){const {data}=await Tesseract.recognize(list[i],'eng+chi_sim+jpn+kor+spa+fra+deu+rus+por+ita');texts.push(data.text||'');$('#ocrStatus').textContent=`正在识别第 ${i+1}/${list.length} 张…`}const text=texts.join('\n');ocrItems=await Promise.all(parseOcrLines(text).map(async item=>({...item,note:await translateToChinese(item.note)})));if(ocrItems.length){const first=ocrItems[0];$('#amount').value=first.amount;$('#category').value=first.category;$('#note').value=first.note;$('#ocrStatus').textContent=`已从 ${list.length} 张图片识别 ${ocrItems.length} 项账目，请确认后一次提交。`;$('#ocrItemsPreview').classList.remove('hidden');$('#ocrItemsPreview').innerHTML=`<div class="ocr-count">待提交账目（${ocrItems.length} 项）</div>`+ocrItems.map((item,index)=>`<div class="ocr-item"><span>${index+1}. ${item.note} · ${item.category}</span><strong>${money(item.amount,$('#sourceCurrency').value)}</strong></div>`).join('')}else{$('#ocrStatus').textContent='未识别到账目，请手动补充第一笔。';const nums=text.match(/\d+[.,]?\d{0,2}/g)||[];if(nums.length)$('#amount').value=nums.map(n=>Number(n.replace(',',''))).filter(n=>n>0).sort((a,b)=>b-a)[0]||'';$('#note').value=text.replace(/\s+/g,' ').trim().slice(0,50)}}catch(err){$('#ocrStatus').textContent='识别服务暂时不可用，请手动填写账目。'}}
async function recognizeFilesSmart(files){const list=[...files].filter(Boolean);if(!list.length)return;openModal('expense','吃喝');$('#ocrStatus').classList.remove('hidden');$('#ocrStatus').textContent=`正在识别 ${list.length} 张图片，请稍候…`;try{const texts=[];for(let i=0;i<list.length;i++){const {data}=await Tesseract.recognize(list[i],'eng+chi_sim+jpn+kor+spa+fra+deu+rus+por+ita');texts.push(data.text||'');$('#ocrStatus').textContent=`正在识别第 ${i+1}/${list.length} 张…`}const text=texts.join('\n');ocrDetectedCurrency=detectReceiptCurrency(text);ocrItems=await Promise.all(parseOcrLines(text).map(async item=>({...item,note:await translateToChinese(item.note)})));if(ocrItems.length){const first=ocrItems[0];fillCurrencies();$('#sourceCurrency').value=ocrDetectedCurrency;$('#targetCurrency').value=localStorage.getItem('ledger:base-currency')||'CNY';$('#amount').value=first.amount;$('#category').value=first.category;$('#note').value=first.note;renderOcrItems();$('#ocrStatus').textContent=`已从 ${list.length} 张图片识别 ${ocrItems.length} 项；原始货币自动设为 ${ocrDetectedCurrency}，请逐项核对后提交。`}else{$('#ocrStatus').textContent='未识别到可靠的逐行金额，请手动补充第一笔。';$('#note').value=text.replace(/\s+/g,' ').trim().slice(0,50)}}catch{$('#ocrStatus').textContent='识别服务暂时不可用，请手动填写账目。'}}
recognize=file=>recognizeFilesSmart([file]);
let batchCameraShots=[];
async function startBatchCamera(){batchCameraShots=[];$('#cameraCount').textContent='已拍 0 张；照片只在本次识别中使用，不会自动保存到手机相册。';if(!navigator.mediaDevices?.getUserMedia){toast('当前浏览器不支持网页摄像头');return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:960}},audio:false});$('#cameraVideo').srcObject=cameraStream;$('#cameraModal').classList.remove('hidden')}catch{toast(location.protocol==='http:'&&!['localhost','127.0.0.1'].includes(location.hostname)?'拍照需要 HTTPS 安全连接':'请允许浏览器使用摄像头')}}
async function captureBatchCamera(){const video=$('#cameraVideo');if(!video.videoWidth){toast('摄像头画面还未准备好');return}const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));batchCameraShots.push(blob);$('#cameraCount').textContent=`已拍 ${batchCameraShots.length} 张；可以继续拍摄或完成识别。`}
function finishBatchCamera(){if(!batchCameraShots.length){toast('请先拍至少一张照片');return}stopCamera();const shots=batchCameraShots;batchCameraShots=[];recognizeFilesSmart(shots)}
let cropQueue=[],cropResults=[],cropIndex=0,cropRect=null,cropDrag=null;
function startCropFlow(files){cropQueue=[...files].filter(Boolean);cropResults=[];cropIndex=0;if(cropQueue.length)openCropStep()}
function openCropStep(){const file=cropQueue[cropIndex],image=$('#cropImage');image.onload=()=>{$('#cropModal').classList.remove('hidden');requestAnimationFrame(()=>{const stage=$('#cropStage'),box=stage.getBoundingClientRect();cropRect={x:box.width*.08,y:box.height*.08,w:box.width*.84,h:box.height*.84};renderCropRect();$('#cropStatus').textContent=`第 ${cropIndex+1}/${cropQueue.length} 张：拖动框选小票区域`})};image.src=URL.createObjectURL(file)}
function renderCropRect(){const rect=$('#cropRect');if(!rect||!cropRect)return;rect.style.left=`${cropRect.x}px`;rect.style.top=`${cropRect.y}px`;rect.style.width=`${cropRect.w}px`;rect.style.height=`${cropRect.h}px`}
function finishCrop(skip=false){const image=$('#cropImage'),stage=$('#cropStage'),box=stage.getBoundingClientRect();if(skip){cropResults.push(cropQueue[cropIndex])}else{const sx=image.naturalWidth/box.width,sy=image.naturalHeight/box.height,canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(cropRect.w*sx));canvas.height=Math.max(1,Math.round(cropRect.h*sy));canvas.getContext('2d').drawImage(image,cropRect.x*sx,cropRect.y*sy,cropRect.w*sx,cropRect.h*sy,0,0,canvas.width,canvas.height);cropResults.push(canvas.toDataURL('image/jpeg',.92))}URL.revokeObjectURL(image.src);$('#cropModal').classList.add('hidden');cropIndex++;if(cropIndex<cropQueue.length)openCropStep();else{const results=cropResults;cropQueue=[];cropResults=[];recognizeFilesSmart(results)}}
function cancelCrop(){cropQueue=[];cropResults=[];$('#cropModal').classList.add('hidden')}
$('#cropStage').addEventListener('pointerdown',event=>{if(!cropRect)return;const box=$('#cropStage').getBoundingClientRect();cropDrag={x:event.clientX-box.left,y:event.clientY-box.top,rect:{...cropRect}};event.currentTarget.setPointerCapture(event.pointerId)});
$('#cropStage').addEventListener('pointermove',event=>{if(!cropDrag)return;const box=$('#cropStage').getBoundingClientRect(),dx=event.clientX-box.left-cropDrag.x,dy=event.clientY-box.top-cropDrag.y;cropRect.x=Math.max(0,Math.min(box.width-cropRect.w,cropDrag.rect.x+dx));cropRect.y=Math.max(0,Math.min(box.height-cropRect.h,cropDrag.rect.y+dy));renderCropRect()});
$('#cropStage').addEventListener('pointerup',()=>{cropDrag=null});
$('#applyCropBtn').onclick=()=>finishCrop(false);$('#skipCropBtn').onclick=()=>finishCrop(true);$('#cancelCropBtn').onclick=cancelCrop;$('#cropModal .modal-backdrop').onclick=cancelCrop;
$('#receiptInput').onchange=e=>{if(e.target.files.length)startCropFlow(e.target.files);e.target.value=''};$('#cameraBtn').onclick=startBatchCamera;$('#captureBtn').onclick=captureBatchCamera;$('#finishCameraBtn').onclick=finishBatchCamera;$('.close-camera').onclick=()=>{batchCameraShots=[];stopCamera()};$('.camera-backdrop').onclick=()=>{batchCameraShots=[];stopCamera()};
bindOcrEditor();
async function restoreSession(){try{const res=await fetch('/api/account',{credentials:'same-origin'});if(!res.ok)return;const data=await res.json();user=data.username;records=data.records;CATS=Array.isArray(data.categories)&&data.categories.length?data.categories:CATS;fillCategories();localStorage.setItem('ledger:current-user',user);$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=user;$('#greeting').textContent='你的记录，只在这里';render();await processPendingShare()}catch{}}
restoreSession();
$('#logoutBtn').onclick=async()=>{try{await fetch('/api/logout',{method:'POST',credentials:'same-origin'})}finally{user='';records=[];localStorage.removeItem('ledger:current-user');$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden');$('#username').focus()}};
const pendingShare=new URLSearchParams(location.search),pendingShareIds=(pendingShare.get('share')||'').split(',').filter(Boolean),pendingShareText=pendingShare.get('sharedText')||'';
async function processPendingShare(){if(!pendingShareIds.length&&!pendingShareText)return;history.replaceState({},'',location.pathname);if(pendingShareIds.length){const id=pendingShareIds[0],response=await fetch(`/shared-import/${encodeURIComponent(id)}`);if(response.ok){const blob=await response.blob();const cache=await caches.open('little-ledger-shared-v1');await cache.delete(`/shared-import/${id}`);await recognize(new File([blob],'shared-receipt.jpg',{type:blob.type||'image/jpeg'}));return}}if(pendingShareText){openModal('expense','吃喝');const items=await Promise.all(parseOcrLines(pendingShareText).map(async item=>({...item,note:await translateToChinese(item.note)})));ocrItems=items;if(items.length){const first=items[0];$('#amount').value=first.amount;$('#category').value=first.category;$('#note').value=first.note;$('#ocrStatus').classList.remove('hidden');$('#ocrStatus').textContent=`已接收 ${items.length} 项分享内容，请核对后保存。`;$('#ocrItemsPreview').classList.remove('hidden');$('#ocrItemsPreview').innerHTML=`<div class="ocr-count">识别明细（${items.length} 项）</div>`+items.map(item=>`<div class="ocr-item"><span>${item.note} · ${item.category}</span><strong>${money(item.amount,$('#sourceCurrency').value)}</strong></div>`).join('')}else{$('#note').value=pendingShareText.slice(0,50);$('#ocrStatus').classList.remove('hidden');$('#ocrStatus').textContent='已接收分享文字，请补充金额和分类后保存。'}}}
let installPrompt=null;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').classList.add('hidden')}else toast('请使用浏览器菜单添加到手机主屏幕')};$('#shareImportBtn').onclick=()=>toast('请在手机分享菜单中选择小账本；苹果手机可使用快捷指令打开本页');$('#loginForm').addEventListener('submit',()=>{let tries=0;const timer=setInterval(()=>{if(user){clearInterval(timer);processPendingShare()}if(++tries>40)clearInterval(timer)},250)});if('serviceWorker' in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});
