const CATS=['娱乐','吃喝','房租','衣服','日常','交通','医疗','学习','其他'];
const CURRENCIES={CNY:'人民币',USD:'美元',EUR:'欧元',JPY:'日元',HKD:'港币',GBP:'英镑',KRW:'韩元',SGD:'新加坡元',AUD:'澳元',CAD:'加元',CHF:'瑞士法郎'};
const icons={娱乐:'♪',吃喝:'🍜',房租:'⌂',衣服:'◌',日常:'⌁',交通:'↗',医疗:'＋',学习:'✦',其他:'•',收入:'＋'};
let user='', records=[], currentType='expense', activeFilter='all', period='month', ocrItems=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function key(){return `ledger:${user}`}
async function saveRecord(record){const res=await fetch(`/api/users/${encodeURIComponent(user)}/records`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(record)});const data=await res.json().catch(()=>null);if(!res.ok)throw new Error(data?.error||'保存失败');return data}
async function removeRecord(id){const res=await fetch(`/api/users/${encodeURIComponent(user)}/records/${encodeURIComponent(id)}`,{method:'DELETE'});if(!res.ok)throw new Error('删除失败')}
function money(n,c='CNY'){try{const digits=Math.abs(Number(n))<1&&Number(n)!==0?4:2;return new Intl.NumberFormat('zh-CN',{style:'currency',currency:c,maximumFractionDigits:digits}).format(Number(n))}catch{return `${c} ${Number(n).toFixed(4)}`}}
function dateLabel(v){return new Date(`${v}T12:00:00`).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}
function today(){return new Date().toISOString().slice(0,10)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function fillCategories(){const select=$('#category');select.innerHTML=CATS.map(c=>`<option>${c}</option>`).join('');$('#categoryFilter').innerHTML='<option value="all">全部分类</option>'+CATS.map(c=>`<option>${c}</option>`).join('')}
function fillCurrencies(){const options=Object.entries(CURRENCIES).map(([code,name])=>`<option value="${code}">${code} · ${name}</option>`).join('');$('#sourceCurrency').innerHTML=options;$('#targetCurrency').innerHTML=options;const base=localStorage.getItem('ledger:base-currency')||'CNY';$('#sourceCurrency').value=base;$('#targetCurrency').value=base}
const rateCache=new Map();
async function getRate(base,target){if(base===target)return 1;const key=`${base}:${target}`;if(rateCache.has(key))return rateCache.get(key);const res=await fetch(`/api/rates?base=${base}&symbols=${target}`);if(!res.ok)throw new Error('汇率服务暂不可用');const data=await res.json();const rate=Number(data.rates?.[target]);if(!rate)throw new Error('未找到该货币汇率');rateCache.set(key,rate);return rate}
async function updateExchangePreview(){const amount=Number($('#amount').value)||0,base=$('#sourceCurrency').value,target=$('#targetCurrency').value;try{const rate=await getRate(base,target);$('#exchangePreview').textContent=`1 ${base} = ${rate.toFixed(6)} ${target} · 记账金额 ${money(amount*rate,target)}`}catch{$('#exchangePreview').textContent='汇率暂时不可用，将按原金额保存，请稍后重试'} }
function openModal(type='expense',cat='吃喝',ocr=''){ocrItems=[];currentType=type;$('#entryModal').classList.remove('hidden');$('#amount').value='';$('#note').value='';$('#date').value=today();$('#category').value=cat;$('#ocrStatus').classList.toggle('hidden',!ocr);$('#ocrStatus').textContent=ocr||'';$('#ocrItemsPreview').classList.add('hidden');$('#ocrItemsPreview').innerHTML='';fillCurrencies();$$('.type-btn').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$('#modalTitle').textContent=ocr?'确认识别结果':'新增一笔';$('#amount').focus()}
function closeModal(){$('#entryModal').classList.add('hidden')}
async function addRecord(e){e.preventDefault();const sourceCurrency=$('#sourceCurrency').value,requestedCurrency=$('#targetCurrency').value;let targetCurrency=requestedCurrency,rate=1,converted=true;try{rate=await getRate(sourceCurrency,requestedCurrency)}catch{targetCurrency=sourceCurrency;converted=false}try{localStorage.setItem('ledger:base-currency',targetCurrency);const drafts=ocrItems.length?ocrItems.map(item=>({...item,type:currentType,date:$('#date').value})): [{type:currentType,amount:Number($('#amount').value),category:$('#category').value,note:$('#note').value.trim()||$('#category').value,date:$('#date').value}];const saved=[];for(const draft of drafts)saved.push(await saveRecord({...draft,sourceAmount:Number(draft.amount),sourceCurrency,currency:targetCurrency,exchangeRate:rate,amount:Number(draft.amount)*rate}));records.unshift(...saved.reverse());closeModal();render();toast(converted?(saved.length>1?`已同步 ${saved.length} 项账目`:'已同步到云端'):(saved.length>1?`汇率暂不可用，已按原货币保存 ${saved.length} 项`:'汇率暂不可用，已按原货币保存'))}catch(err){toast(err.message==='Failed to fetch'?'云端服务未连接，请稍后重试':'云端保存失败，请稍后重试')}}
function filtered(){const cat=$('#categoryFilter').value;return records.filter(r=>(activeFilter==='all'||r.type===activeFilter)&&(cat==='all'||r.category===cat))}
function txHtml(r,del=true){return `<div class="transaction"><span class="tx-icon ${r.type==='income'?'green':'coral'}">${icons[r.category]||'•'}</span><div class="tx-main"><b>${r.note||r.category}</b><small>${r.category} · ${dateLabel(r.date)}${r.sourceCurrency&&r.sourceCurrency!==r.currency?` · ${r.sourceAmount} ${r.sourceCurrency}`:''}</small></div><strong class="tx-amount ${r.type}">${r.type==='income'?'+':'-'}${money(r.amount,r.currency||'CNY')}</strong>${del?`<button class="delete-btn" data-delete="${r.id}" title="删除"><i data-lucide="trash-2"></i></button>`:''}</div>`}
function renderHome(){const ym=today().slice(0,7), rs=records.filter(r=>r.date.startsWith(ym)), inc=rs.filter(r=>r.type==='income').reduce((a,r)=>a+r.amount,0), exp=rs.filter(r=>r.type==='expense').reduce((a,r)=>a+r.amount,0);$('#currentMonth').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long'});$('#todayLabel').textContent=dateLabel(today());$('#monthBalance').textContent=money(inc-exp);$('#monthIncome').textContent=`收入 ${money(inc)}`;$('#monthExpense').textContent=`支出 ${money(exp)}`;$('#recentList').innerHTML=records.slice(0,5).map(r=>txHtml(r,false)).join('')||'<div class="empty">还没有记录，先记下今天的第一笔吧。</div>'}
function renderLedger(){$('#ledgerList').innerHTML=filtered().map(r=>txHtml(r)).join('')||'<div class="empty">没有符合条件的记录。</div>'}
function renderDashboard(){const now=new Date(), val=$('#periodSelect').value||now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0'), rs=records.filter(r=>period==='year'?r.date.startsWith(val):r.date.startsWith(val)), exp=rs.filter(r=>r.type==='expense'),inc=rs.filter(r=>r.type==='income'), totalExp=exp.reduce((a,r)=>a+r.amount,0),totalInc=inc.reduce((a,r)=>a+r.amount,0), groups=CATS.map(c=>[c,exp.filter(r=>r.category===c).reduce((a,r)=>a+r.amount,0)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);let angle=0,colors=['#e9644c','#e6b65a','#79a77e','#76a5c9','#8d7aac','#d18c68'];const parts=groups.map((g,i)=>{const start=angle;angle+=totalExp?g[1]/totalExp*100:0;return `${colors[i%colors.length]} ${start}% ${angle}%`}).join(',')||'#ddd 0 100%';$('#dashboardContent').innerHTML=`<div class="chart-wrap"><div class="donut" style="background:conic-gradient(${parts})"><span>${money(totalExp)}</span></div><div class="legend">${groups.slice(0,5).map((g,i)=>`<div class="legend-row"><span><i class="dot" style="background:${colors[i%colors.length]}"></i>${g[0]}</span><b>${money(g[1])}</b></div>`).join('')||'<div class="muted">该时段暂无支出</div>'}</div></div><table class="stat-table"><tbody><tr><td>总收入</td><td class="income">${money(totalInc)}</td></tr><tr><td>总支出</td><td>${money(totalExp)}</td></tr><tr class="table-total"><td>实际结余</td><td>${money(totalInc-totalExp)}</td></tr>${groups.map(g=>`<tr><td>${g[0]} · ${((g[1]/(totalExp||1))*100).toFixed(1)}%</td><td>${money(g[1])}</td></tr>`).join('')}</tbody></table><div class="section-head"><h3>金额最大的 10 笔</h3><span class="muted">${period==='year'?'年度':'月度'}</span></div><div class="top-list">${[...rs].sort((a,b)=>b.amount-a.amount).slice(0,10).map(r=>`<div class="top-row"><div class="tx-main"><b>${r.note}</b><small>${r.category} · ${dateLabel(r.date)}</small></div><strong class="tx-amount ${r.type}">${r.type==='income'?'+':'-'}${money(r.amount)}</strong></div>`).join('')||'<div class="empty">还没有可分析的交易。</div>'}</div>`}
function renderPeriodSelect(){const y=new Date().getFullYear();$('#periodSelect').innerHTML=period==='year'?Array.from({length:5},(_,i)=>`<option>${y-i}</option>`).join(''):Array.from({length:12},(_,i)=>{const d=new Date(y,i,1);return `<option value="${y}-${String(i+1).padStart(2,'0')}">${y}年${i+1}月</option>`}).join('');renderDashboard()}
function render(){renderHome();renderLedger();renderPeriodSelect();lucide.createIcons()}
function guessCategory(text){return CATS.find(c=>text.includes(c))||(['猪肉','牛肉','鸡','菜','饭','餐','奶茶','咖啡','水果','超市'].some(x=>text.includes(x))?'吃喝':['地铁','公交','打车','滴滴','高铁','火车','停车'].some(x=>text.includes(x))?'交通':['房租','租金'].some(x=>text.includes(x))?'房租':['电影','游戏','门票'].some(x=>text.includes(x))?'娱乐':'其他')}
function parseOcrLines(text){const skip=/^(合计|总计|应付|实付|找零|税额|税率|优惠|折扣|发票|订单|支付|二维码|收款|金额|小计|服务费)/;const amountPattern=/(\d{1,6}(?:[,.]\d{1,2})?)\s*(?:元|円|¥|￥|usd|rmb)?\s*$/i;return text.split(/\r?\n/).map(line=>line.replace(/\s+/g,' ').trim()).filter(line=>line&&!skip.test(line)).map(line=>{const match=line.match(amountPattern);if(!match)return null;const amount=Number(match[1].replace(',',''));const note=line.slice(0,match.index).replace(/[|:：*x×]+$/,'').trim();return amount>0&&amount<1000000?{amount,category:guessCategory(note),note:note||'识别账目'}:null}).filter(Boolean)}
async function translateToChinese(text){if(!text||/[\u4e00-\u9fff]/.test(text))return text;try{const q=encodeURIComponent(text.slice(0,300));const res=await fetch(`https://api.mymemory.translated.net/get?q=${q}&langpair=autodetect|zh-CN`);const data=await res.json();return data.responseData?.translatedText||text}catch{return text}}
async function recognize(file){openModal('expense','吃喝');$('#ocrStatus').classList.remove('hidden');$('#ocrStatus').textContent='正在识别多语言账目并转换为中文…';try{const {data}=await Tesseract.recognize(file,'eng+chi_sim+jpn+kor+spa+fra+deu+rus+por+ita');const text=data.text||'';ocrItems=await Promise.all(parseOcrLines(text).map(async item=>({...item,note:await translateToChinese(item.note)})));if(ocrItems.length){const first=ocrItems[0];$('#amount').value=first.amount;$('#category').value=first.category;$('#note').value=first.note;$('#ocrStatus').textContent=`已识别 ${ocrItems.length} 项并完成中文化尝试，请核对后保存。`;$('#ocrItemsPreview').classList.remove('hidden');$('#ocrItemsPreview').innerHTML=`<div class="ocr-count">识别明细（${ocrItems.length} 项）</div>`+ocrItems.map(item=>`<div class="ocr-item"><span>${item.note} · ${item.category}</span><strong>${money(item.amount,$('#sourceCurrency').value)}</strong></div>`).join('')}else{$('#ocrStatus').textContent='未识别到逐行金额，请手动补充第一笔。';const nums=text.match(/\d+[.,]?\d{0,2}/g)||[];if(nums.length)$('#amount').value=nums.map(n=>Number(n.replace(',',''))).filter(n=>n>0).sort((a,b)=>b-a)[0]||'';$('#note').value=text.replace(/\s+/g,' ').trim().slice(0,50)}}catch(err){$('#ocrStatus').textContent='识别服务暂时不可用，请手动填写账目。'}}
$('#logoutBtn').onclick=()=>{user='';localStorage.removeItem('ledger:current-user');records=[];$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden');$('#username').focus()};$('#quickAdd').onclick=()=>openModal();$('#viewAll').onclick=()=>switchTab('ledgerTab');$('#uploadBtn').onclick=()=>$('#receiptInput').click();$('#receiptInput').onchange=e=>e.target.files[0]&&recognize(e.target.files[0]);$('#entryForm').onsubmit=addRecord;$('.close-modal').onclick=closeModal;$('.modal-backdrop').onclick=closeModal;$$('.type-btn').forEach(b=>b.onclick=()=>{currentType=b.dataset.type;$$('.type-btn').forEach(x=>x.classList.toggle('active',x===b))});$$('.nav-item').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));function switchTab(id){$$('.tab-page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));render()};$$('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderLedger();lucide.createIcons()});$('#categoryFilter').onchange=renderLedger;$$('.period').forEach(b=>b.onclick=()=>{period=b.dataset.period;$$('.period').forEach(x=>x.classList.toggle('active',x===b));renderPeriodSelect()});$('#periodSelect').onchange=renderDashboard;fillCategories();lucide.createIcons();
const remembered=localStorage.getItem('ledger:current-user');if(remembered)$('#username').value=remembered;
let loginBusy=false;
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(loginBusy)return;loginBusy=true;const name=$('#username').value.trim(),password=$('#password').value;$('#loginError').textContent='';try{const res=await fetch('/api/account',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:name,password})});const type=res.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('当前页面不是云端服务，请先用 npm start 启动 Node 服务');const data=await res.json();if(!res.ok)throw new Error(data.error||'登录失败');user=data.username;records=data.records;localStorage.setItem('ledger:current-user',user);$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=user;$('#greeting').textContent='你的记录，只在这里';render()}catch(err){localStorage.removeItem('ledger:current-user');$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden');$('#loginError').textContent=err.message==='Failed to fetch'?'云端服务未连接，请稍后再试':err.message}finally{loginBusy=false}});
$('#togglePassword').onclick=()=>{const input=$('#password'),button=$('#togglePassword');input.type=input.type==='password'?'text':'password';button.setAttribute('aria-label',input.type==='password'?'显示密码':'隐藏密码');button.innerHTML=`<i data-lucide="${input.type==='password'?'eye':'eye-off'}"></i>`;lucide.createIcons()};
$('#amount').addEventListener('input',updateExchangePreview);$('#sourceCurrency').addEventListener('change',updateExchangePreview);$('#targetCurrency').addEventListener('change',updateExchangePreview);
document.addEventListener('click',async e=>{const btn=e.target.closest('[data-delete]');if(btn&&confirm('确定删除这笔记录吗？')){try{await removeRecord(btn.dataset.delete);records=records.filter(r=>r.id!==btn.dataset.delete);render();toast('记录已删除')}catch(err){toast(err.message==='Failed to fetch'?'云端服务未连接，请稍后重试':(err.message||'云端删除失败，请稍后重试'))}}});
let cameraStream=null;
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){toast('当前浏览器不支持网页摄像头');return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:960}},audio:false});$('#cameraVideo').srcObject=cameraStream;$('#cameraModal').classList.remove('hidden')}catch(err){toast(location.protocol==='http:'&&!['localhost','127.0.0.1'].includes(location.hostname)?'拍照需要 HTTPS 安全连接':'请允许浏览器使用摄像头')}}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}$('#cameraVideo').srcObject=null;$('#cameraModal').classList.add('hidden')}
async function captureCamera(){const video=$('#cameraVideo');if(!video.videoWidth){toast('摄像头画面还未准备好');return}const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));stopCamera();recognize(blob)}
$('#cameraBtn').onclick=startCamera;$('#captureBtn').onclick=captureCamera;$('.close-camera').onclick=stopCamera;$('.camera-backdrop').onclick=stopCamera;
$$('.quick-item').forEach(button=>{button.setAttribute('aria-label',`记录${button.dataset.cat}`);button.onclick=()=>openModal(button.dataset.type,button.dataset.cat)});
